apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-volume-controller
subjects:
  - kind: ServiceAccount
    name: default # Name is case sensitive
    namespace: velero 
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: leaselock
  apiGroup: rbac.authorization.k8s.io
