apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-volume-controller
  namespace: velero
  labels:
    app: velero-volume-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-volume-controller
  template:
    metadata:
      labels:
        app: velero-volume-controller
    spec:
      containers:
      - name: velero-volume-controller
        image: cjyar/velero-volume-controller 
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config
            mountPath: /velero-volume-controller/examples
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: velero-volume-controller
